# --- Cấu hình Database Aiven ---
spring.datasource.url=jdbc:mysql://mysql-5480e2d-tien1103-0b49.f.aivencloud.com:20811/defaultdb?useSSL=true&serverTimezone=UTC
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_md-KMzAHfi5BDfK0D26

# --- Cấu hình Port cho Render ---
server.port=${PORT:8080}

# --- Google Apps Script (Quên mật khẩu) ---
google.script.url=https://script.google.com/macros/s/AKfycbyIrUC2zne5LCTSShOkJLPVB20jSmH_n07WZ1KuLM5NpyDWkJuUuPztcfxHR3qVp0l7dA/exec

# --- Cấu hình JPA/Hibernate ---
# Đổi none thành update để Hibernate tự tạo thêm cột otp_code và otp_expiry nếu thiếu
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# --- Cấu hình VNPay Sandbox ---
payos.clientId=11fda14f-01ad-4d2f-95c6-fae3eea285e3
payos.apiKey=ead77c5c-1961-464f-a0e8-a1b928d92452
payos.checksumKey=8094d62c015f4211c3c3e16d628e2c1e397a20c1f09bce088b72c57b01362ca5