#spring.datasource.url=jdbc:mysql://mysql-5480e2d-tien1103-0b49.f.aivencloud.com:20811/defaultdb?useSSL=true&serverTimezone=UTC
#spring.datasource.username=avnadmin
#spring.datasource.password=${DB_PASSWORD}
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
# Port ?? ch?y web (m?c ??nh là 8080)
server.port=8080

# C?u hình n?i t?i WAMP / XAMPP (Localhost)
spring.datasource.url=jdbc:mysql://localhost:3306/coffee_db
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# T? ??ng t?o b?ng d?a trên file User.java c?a b?n
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true