spring.datasource.url=jdbc:mysql://mysql-5480e2d-tien1103-0b49.f.aivencloud.com:20811/defaultdb?useSSL=true&serverTimezone=UTC
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_md-KMzAHfi5BDfK0D26


spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# --- Cấu hình VNPay Sandbox ---
# (Bạn thay MÃ_CỦA_BẠN bằng thông tin hệ thống gửi qua email nhé)
vnpay.tmnCode=VMQ1U37K
vnpay.hashSecret=WZ4CRU673JYLA8KD1E2KRW6F3ECGZHSZ
vnpay.url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
# Link ứng dụng backend của bạn để đón CallBack
vnpay.returnUrl=http://localhost:8080/checkout/vnpay-return